### ISSUE TITLE
Crash everytime try to recover this deleted vod

### ISSUE THREAD

**Issue by JihedKrounaCegep** [TwitchRecover/TwitchRecover#115]
VOD Recovery:
To recover a VOD (time limit of maximum 60 days), you can either:
1. Use a stream analytics link.
(Supports stream links from Twitch Tracker and Stream Charts)
2. Input values manually.
Please enter the number of the option you want to select (number between 1-2 inclusive): 1

Please enter the stream analytics link (supports Twitch Tracker and Stream Charts): https://twitchtracker.com/bob7/streams/41840044125
Exception in thread "main" java.lang.NullPointerException
        at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
        at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
        at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
        at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by Birdwards** [comment]
I get this same error while entering values manually (channel: birdwards, id: 966415888); it crashes after I enter the start time.
