### ISSUE TITLE
issue  with the lastest verison

### ISSUE THREAD

**Issue by johno456666** [TwitchRecover/TwitchRecover#123]
hi i never has issues    put when i ma downloading a  sub only  video   i put in   the location i get this error  once downloading   

incorrect input     i know i  got  location  of the  folder  is thier  but it wont save

**Comment by marcmy** [comment]
I'm getting this: 

Exception in thread "main" java.lang.NumberFormatException: For input string: "url here"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at TwitchRecover.Core.VODRetrieval.retrieveID(VODRetrieval.java:83)
        at TwitchRecover.Core.VOD.retrieveID(VOD.java:271)
        at TwitchRecover.CLI.Handlers.VODHandler.download(VODHandler.java:70)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:41)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)

It's worth noting that I just updated or reinstalled java SE a couple days ago.
