### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because "date" is null

### ISSUE THREAD

**Issue by DoyunShin** [TwitchRecover/TwitchRecover#141]
VOD Recovery:
To recover a VOD (time limit of maximum 60 days), you can either:
1. Use a stream analytics link.
(Supports stream links from Twitch Tracker and Stream Charts)
2. Input values manually.
Please enter the number of the option you want to select (number between 1-2 inclusive): 1

Please enter the stream analytics link (supports Twitch Tracker and Stream Charts): https://twitchtracker.com/e_saem/streams/42555741181
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because "date" is null
        at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
        at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
        at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
        at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by HeavyLogic** [comment]
I have exactly the same error. I picked 5, then 1, then pasted this link: https://streamscharts.com/channels/m3_dic/streams/39973088808

**Comment by ghost** [comment]
@HeavyLogic Vod does not exist unfortunately.
