### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by rmfkdehd** [TwitchRecover/TwitchRecover#155]
When I run it as an exe file on Windows, the cli just turns off.
When I run it as a jar file in Ubuntu, I get the following error...

Exception in thread "main" org.json.JSONException: JSONObject["videoPlaybackAccessToken"] is not a JSONObject.
	at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2581)
	at org.json.JSONObject.getJSONObject(JSONObject.java:786)
	at TwitchRecover.Core.API.API.parseToken(API.java:178)
	at TwitchRecover.Core.API.API.getToken(API.java:226)
	at TwitchRecover.Core.API.VideoAPI.getVODToken(VideoAPI.java:114)
	at TwitchRecover.Core.API.VideoAPI.getVODFeeds(VideoAPI.java:50)
	at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:150)
	at TwitchRecover.CLI.Handlers.VODHandler.download(VODHandler.java:71)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:41)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by rmfkdehd** [comment]
Here is the full log.

DISCLAIMER:
This is only the alpha version of this program.
This should not be treated as a complete and final program.
There may be bugs and issues, which if you do experience please report on the Github project page - https://github.com/twitchrecover/twitchrecover
Thank you for your understanding.

Welcome to Twitch Recover!
The number one Twitch recovery tool created by Daylam Tayari (https://github.com/daylamtayari)
If you like this tool please help support me: https://paypal.me/daylamtayari https://cash.app/$daylamtayari BTC: 15KcKrsqW6DQdyZPrgRXXmsKkyyZzHAQVX


Menu:
Streams:
1. Get a live stream link (get the M3U8 stream link of a live stream).
2. Download a stream live. (Currently unavailable, coming in the beta)

VODs:
3. Get the link to a VOD (including sub-only).
4. Download a VOD (including sub-only).
5. Recover a VOD - 60 days maximum (can be less in rare cases).

Highlights:
6. Retrieve the link to a highlight.
7. Download a highlight.
8. Recover a highlight.

Videos:
9. Check if a VOD/highlight has muted segments.
10. 'Unmute' a VOD/highlight (be able to view the muted segments of the M3U8).
11. Download an M3U8 file.
12. Convert a TS file to MP4.

Clips:
13. Retrieve permanent link of a clip - never deleted.
14. Download a clip.
15. Recover ALL clips from a stream - NO time limit.

Mass options: (Currently unavailable, coming in the beta)
16. Mass recover options. (Currently unavailable, coming in the beta)
17. Mass download options. (Currently unavailable, coming in the beta)
Please enter the number of the option you want to select (number between 1-17 inclusive): 9

Muted segments check:
Please enter the link of the M3U8 to check: https://www.twitch.tv/videos/1076277111

M3U8 DOES NOT contain any muted segments.

Do you want to check another video?
Enter y for yes and n for no: n


Do you want to continue using the program/perform a new operation?
Please enter 'y' for yes and 'n' for no: y


Menu:
Streams:
1. Get a live stream link (get the M3U8 stream link of a live stream).
2. Download a stream live. (Currently unavailable, coming in the beta)

VODs:
3. Get the link to a VOD (including sub-only).
4. Download a VOD (including sub-only).
5. Recover a VOD - 60 days maximum (can be less in rare cases).

Highlights:
6. Retrieve the link to a highlight.
7. Download a highlight.
8. Recover a highlight.

Videos:
9. Check if a VOD/highlight has muted segments.
10. 'Unmute' a VOD/highlight (be able to view the muted segments of the M3U8).
11. Download an M3U8 file.
12. Convert a TS file to MP4.

Clips:
13. Retrieve permanent link of a clip - never deleted.
14. Download a clip.
15. Recover ALL clips from a stream - NO time limit.

Mass options: (Currently unavailable, coming in the beta)
16. Mass recover options. (Currently unavailable, coming in the beta)
17. Mass download options. (Currently unavailable, coming in the beta)
Please enter the number of the option you want to select (number between 1-17 inclusive): 4

VOD downloading:
Please enter the link of the VOD to download: 1076277111


ERROR: Invalid VOD link.
Please enter a valid VOD URL.https://www.twitch.tv/videos/1076277111
Exception in thread "main" org.json.JSONException: JSONObject["videoPlaybackAccessToken"] is not a JSONObject.
	at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2581)
	at org.json.JSONObject.getJSONObject(JSONObject.java:786)
	at TwitchRecover.Core.API.API.parseToken(API.java:178)
	at TwitchRecover.Core.API.API.getToken(API.java:226)
	at TwitchRecover.Core.API.VideoAPI.getVODToken(VideoAPI.java:114)
	at TwitchRecover.Core.API.VideoAPI.getVODFeeds(VideoAPI.java:50)
	at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:150)
	at TwitchRecover.CLI.Handlers.VODHandler.download(VODHandler.java:71)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:41)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by rmfkdehd** [comment]
sorry...
It was my mistake.
Everything is normal.
