### ISSUE TITLE
Crashes after I enter streamcharts link

### ISSUE THREAD

**Issue by hasnogaems** [TwitchRecover/TwitchRecover#193]
This tool still suppose to work right?

**Comment by nanspudding** [comment]
mine does the same thing when I use the twitch tracker link

**Comment by samuel-cazelli** [comment]
Mine does it aswell. 

Here the exception it throws:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because "date" is null
        at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
        at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
        at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
        at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by devOSRS** [comment]
any updates?

**Comment by shivamrewa9981** [comment]
> Try the [release](https://github.com/PaaaulZ/TwitchRecover/releases) from @PaaaulZ's fork

is he trusted? have you tried his version of twitchrecover ?

**Comment by RichConnerGMN** [comment]
> Try the [release](https://github.com/PaaaulZ/TwitchRecover/releases) from @PaaaulZ's fork

i tried this, the only difference was that it waited a bit to close after pasting in the link
