### ISSUE TITLE
twitchrecover isn't working?(get m3u8)

### ISSUE THREAD

**Issue by qa159123** [TwitchRecover/TwitchRecover#219]
I can see vod on the streamer's video. but twitchrecover's No.5 fuction(Recover a VOD) not working

twitchrecover is blocked?

**Comment by ItIckeYd** [comment]
@qa159123 twitchtracker link?

**Comment by qa159123** [comment]
yes....

**Comment by ItIckeYd** [comment]
@qa159123 can you provide it?

**Comment by qa159123** [comment]
https://twitchtracker.com/winter_28270/streams/39305085543

**Comment by qa159123** [comment]
I got m3u8 but not use twitchrecover.....

**Comment by ItIckeYd** [comment]
@qa159123 twitchrecover does not have latest domains... it cannot recover vods on new domains.

**Comment by qa159123** [comment]
have you use twitchrecover or something else??

**Comment by ItIckeYd** [comment]
You can use python script contained here -> https://github.com/ItIckeYd/VodRecovery

**Comment by qa159123** [comment]
Then how did you get those link??

**Comment by ItIckeYd** [comment]
@qa159123 The python script that I just sent the link to..

**Comment by qa159123** [comment]
should I download all three files?

**Comment by ItIckeYd** [comment]
@qa159123 You only need the python script are you familiar with running code? If not it might be a little hard for you to use unless you look it up. I recommend using either visual studio code or pycharm.

**Comment by qa159123** [comment]
![image](https://user-images.githubusercontent.com/105062948/167157081-0887d8ff-b65d-44d5-a01f-30d58d006cdb.png)

Actually tried a few times but it didn't work

**Comment by ItIckeYd** [comment]
@qa159123  Are you using local time? my time is UTC-3 which is local for me and it works properly.

**Comment by qa159123** [comment]
![image](https://user-images.githubusercontent.com/105062948/167158430-dff9ddd0-b1ae-43b5-b4ff-eb63ffc4800b.png)

That was try another thing
anyway it doeasn't working.....
I tried time differently too.....

**Comment by ItIckeYd** [comment]
@qa159123  Where are you from? 

Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-05-04 06:04:00
https://d3vd9lfkzbru3h.cloudfront.net/50b8e24d2cd9b6c1e854_winter_28270_39302689111_1651655077/chunked/index-dvr.m3u8
https://d1mhjrowxxagfy.cloudfront.net/50b8e24d2cd9b6c1e854_winter_28270_39302689111_1651655077/chunked/index-dvr.m3u8

**Comment by qa159123** [comment]
![image](https://user-images.githubusercontent.com/105062948/167159435-ab137fe7-1923-411f-90bc-39ad4c73d28c.png)

I'm form Korea....
I try what you sent it but not working......

is it copy this scprit paste to pythone IDLE?
![image](https://user-images.githubusercontent.com/105062948/167159823-53727d7b-9577-42aa-8318-710fc94609e0.png)

![image](https://user-images.githubusercontent.com/105062948/167159871-7ee147e0-463e-4f85-b50c-d0f7003f02b3.png)

**Comment by ItIckeYd** [comment]
@qa159123 

Enter streamer name: winter_28270
Enter vod id: 39302689111
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-05-04 18:04:00

**Comment by qa159123** [comment]
WOW IT WORK!!
The Problem Is the time!!
Thank you!!
You are my Obi-Wan Kenobi

**Comment by ItIckeYd** [comment]
@qa159123  lol.. yeah its based off local time so korea is GMT+9... so if you are using twitchtracker and on the top right it says UTC you need to add 9 hours to the start time of the vods.

**Comment by qa159123** [comment]
Yes Master!!

**Comment by jientz** [comment]
@ItIckeYd I've tried using your script as well and had some issues, was wondering if you could have a look?

Stream tracker link: https://twitchtracker.com/badmanlarry/streams/46393175021
VOD Link: https://www.twitch.tv/videos/1483153557 (Subscriber only)
Sullygnome Link (UTC timezone): https://sullygnome.com/channel/badmanlarry/stream/46393175021

My input has been the following:

`
Enter Streamer Name: BadmanLarry
Enter vod id: Enter vod id: 46393175021
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS): 2022-05-13 19:00:00

`

And I've gotten a huge error (below). I wonder if it has something to do with how I've installed the script (I have python + pycharm + requests module) or if it is because I don't have a precise timestamp to the nearest second? 

Thanks

Error:

`Traceback (most recent call last):
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vod-secure.twitch.tv', port=443): Max retries exceeded with url: /2110d21e70ff0ece1917_BadmanLarry_46393175021_1652464800/chunked/index-dvr.m3u8 (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\keanu\Downloads\Vodrecovery\VodRecovery-main\RecoverVod.py", line 179, in <module>
    recover_vod()
  File "C:\Users\keanu\Downloads\Vodrecovery\VodRecovery-main\RecoverVod.py", line 156, in recover_vod
    if get_valid_links():
  File "C:\Users\keanu\Downloads\Vodrecovery\VodRecovery-main\RecoverVod.py", line 95, in get_valid_links
    response_list = list(pool.map(get_url, batch))
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\keanu\Downloads\Vodrecovery\VodRecovery-main\RecoverVod.py", line 56, in get_url
    return requests.get(url,stream=True)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\keanu\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='vod-secure.twitch.tv', port=443): Max retries exceeded with url: /2110d21e70ff0ece1917_BadmanLarry_46393175021_1652464800/chunked/index-dvr.m3u8 (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))
`

**Comment by ItIckeYd** [comment]
@jientz 

On streamscharts it looks like the vod is split up into two separate broadcasts the only broadcast I could retrieve is the second one 6 hours 55 minutes.. doesn't look like the first one exists anymore.

https://d1m7jfoe9zdc1j.cloudfront.net/cf70af64b2cea1e56ae7_badmanlarry_46394611229_1652482507/chunked/index-dvr.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/cf70af64b2cea1e56ae7_badmanlarry_46394611229_1652482507/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

as for the error i'm not exactly sure but it looks like a disconnect between the version your running and the one i'm running.

My Path - C:\Users\User\AppData\Local\Programs\Python\**Python38**
Your Path - C:\Users\User\AppData\Local\Programs\Python\**Python310**

You could try download python 3.8 but I cant guarantee you that is the problem.

If you go into command prompt and type "python --version" it will tell you the version just to confirm.
