### ISSUE TITLE
can't download anything: VODS download, clips, recover

### ISSUE THREAD

**Issue by rubicon31** [TwitchRecover/TwitchRecover#419]
option 4: download VOD, when it's analyzing the link it just closes itself (had same issue in the past when domains werent updated)
eg. https://www.twitch.tv/videos/1679733320?filter=archives&sort=time

option 5: recover a VOD, same as above
eg. https://streamscharts.com/channels/sig5569/streams/40013781767 (it's a day old)

option 14: download a clip, says it's downloaded but file is not created, it's not even in temp folder 
eg. https://www.twitch.tv/sig5569/clip/EsteemedAverageSnakeOSkomodo-SV0LSp1xW9NYGAwq?filter=clips&range=30d&sort=time

tested on windows 2 different pcs, one it's latest update but the other is still version 21h2, still have to try linux

**Comment by Jeen019** [comment]
on linux gives the error
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:97)
	at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:152)
	at TwitchRecover.CLI.Handlers.VODHandler.download(VODHandler.java:71)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:41)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)
