### ISSUE TITLE
Program closing itself

### ISSUE THREAD

**Issue by Kanokij** [TwitchRecover/TwitchRecover#465]
After choosing an option and entering the link, the program crashes and closes itself. I tried completely uninstallign and reinstalling nothing changes. Any help?

**Comment by zabdos** [comment]
i'm experiencing the same problem right now dont know how to fix it

**Comment by lucasrecan** [comment]
Same here, windows 11

**Comment by scrouncha** [comment]
when launching from cmd, it shows this error : 
`Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
        at org.json.JSONObject.<init>(JSONObject.java:222)
        at org.json.JSONObject.<init>(JSONObject.java:406)
        at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:85)
        at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:152)
        at TwitchRecover.CLI.Handlers.VODHandler.retrieve(VODHandler.java:57)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:38)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)`

**Comment by scrouncha** [comment]
#455 first answer is working

**Comment by massicadenti** [comment]
Workaround:

1. Go to https://twitchtracker.com/ , search for the channel, then open it and copy the link at the streaming you want to download (right click on the date), is something like: https://twitchtracker.com/NAMECHANNEL/streams/XXXXXXXXX (where XXXXXXXX is different from the link on twitch.tv )
2. Use TwitchRecover, option 5 (Recover a VOD) -> 1 (Use a stream analytics link), paste the link of streaming on TwitchTracker, get the .m3u8 link (is on cloudfront.com , not on twitch)
3. Use TwitchRecover, option 11 (Download a M3U8 file) -> paste the cloudfront .m3u8 link (including .m3u8 extension), give the path where you want to download the video, select mp4 or other container as usual

I hope I was helpful
