### ISSUE TITLE
Issue downloading VOD in Twitch Recover (Windows and Mac OS) 

### ISSUE THREAD

**Issue by FunkDoctaSpockBrickCity** [TwitchRecover/TwitchRecover#466]
I've noticed an issue with Twitch Recover. This issue has been happening for a couple of weeks now. When I paste the VOD link into terminal on Mac it gives me this coded error message. On the Windows version, the Twitch Recover app crashes when I paste a VOD link. Is anyone else having this same issue? Is it a Twitch issue or a Twitch Recover issue? 

<img width="561" alt="Screenshot 2023-03-19 at 1 41 58 PM" src="https://user-images.githubusercontent.com/128324859/226207823-73dcec69-99fc-44a5-8359-4f606fba376a.png">

**Comment by lucasrecan** [comment]
I have the same issue, on windows 11

**Comment by massicadenti** [comment]
Workaround:

1. Go to https://twitchtracker.com/ , search for the channel, then open it and copy the link at the streaming you want to download (right click on the date), is something like: https://twitchtracker.com/NAMECHANNEL/streams/XXXXXXXXX (where XXXXXXXX is different from the link on twitch.tv )
2. Use TwitchRecover, option 5 (Recover a VOD) -> 1 (Use a stream analytics link), paste the link of streaming on TwitchTracker, get the .m3u8 link (is on cloudfront.com , not on twitch)
3. Use TwitchRecover, option 11 (Download a M3U8 file) -> paste the cloudfront .m3u8 link (including .m3u8 extension), give the path where you want to download the video, select mp4 or other container as usual

I hope I was helpful

**Comment by Divin1ty666** [comment]
Hello! I have the same issue when I try to download sub-only VODs. I've tried this workaround but second step makes Twitch Recover crash as well

> Exception in thread "main" java.lang.NullPointerException
>         at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
>         at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
>         at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
>         at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
>         at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
>         at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
>         at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by gegeletesteur** [comment]
Same issue, but @massicadenti thanks for the workaround : it helped ! 👍
