### ISSUE TITLE
Streamcharts links crash program

### ISSUE THREAD

**Issue by Ashdemai** [TwitchRecover/TwitchRecover#507]
I'm using Arch Linux, Using the latest version (2.0a). Entering streamcharts link crashes the program

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because "date" is null
	at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
	at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
	at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
	at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)
```

Same link works with a Twitchtracker link.

**Comment by ghost** [comment]
@Ashdemai  

Due to TwitchRecover code being outdated (2 years) it still uses the old Streamscharts API which is now deprecated.

**Comment by VendenIX** [comment]
Is there another version that currently works?

**Comment by ghost** [comment]
@VendenIX Here is an alternative...

https://github.com/Shishkebaboo/VodRecovery
