### ISSUE TITLE
crash when trying to download a subs only VOD

### ISSUE THREAD

**Issue by Felzow47** [TwitchRecover/TwitchRecover#584]

**Comment by PeterPedro** [comment]
same, I'm using the jar, error message

Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
        at org.json.JSONObject.<init>(JSONObject.java:222)
        at org.json.JSONObject.<init>(JSONObject.java:406)
        at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:85)
        at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:152)
        at TwitchRecover.CLI.Handlers.VODHandler.retrieve(VODHandler.java:57)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:38)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)
