### ISSUE TITLE
Window closes after trying to recover VOD

### ISSUE THREAD

**Issue by alfonso-cau** [TwitchRecover/TwitchRecover#671]
After selecting the option "Recover a VOD" and selecting the option "Use a stream analytics link." and pressing enter, the app closes by itself without showing the error or indicating what failed.

https://github.com/user-attachments/assets/7f09f38f-af10-4aba-bce9-eaf52f86caee

**Comment by FBN216** [comment]
It looks like Twitch Tracker and Stream Charts have changed something. That's the error I'm getting:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because "date" is null
        at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
        at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
        at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
        at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)
